config/routes.rb
Shizit::Application.routes.draw do
	get '/activity', to: 'its#activity'

	resources :its do
		member do
			get 'activity'
		end

		resources :categories do
			resources :contents do
				member do
					get 'pic'
				end
				resources :comments
			end
		end
	end

	devise_for :users

	root to: 'its#show'
end

app/models/content.rb
class Content < ActiveRecord::Base
  include Humanizer
  require_human_on :create
	default_scope { where(in_recycling: false) }
	has_many :comments
	belongs_to :category, :counter_cache => true
	after_save :update_counter_cache
	after_destroy :update_counter_cache
	self.per_page = 10
	
	def self.inherited(child)
		child.instance_eval do
			def model_name
				Content.model_name
			end
		end
		super
	end
	
	def came_from
	  self.name
	end
	
	def image_file=(input_data)
		self.file_name = input_data.original_filename
		self.file_type = input_data.content_type.chomp
		self.image_data = input_data.read
	end
	
	def to_param
		"#{id}-#{title.gsub(/[^a-z0-9]+/i, '-')}"
	end

	def update_counter_cache
		count = Content.where(in_recycling: false, category_id: self.category.id).count
		self.category.update(active_contents_count: count)
	end
  
  def update_click_counter
    self.click_count = self.click_count + 1
    self.save
  end
  
end

app/models/content_type.rb
class ContentType < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  #before_filter :authenticate_user!, :except => [:show, :pic]
  load_and_authorize_resource :only => [:delete, :update]

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])
    @it = @content.category.it
    @content.update_click_counter
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    it = It.find(params[:it_id])
	  if !it.locked
  		@content = Content.new
  		@content.category = Category.find(params[:category_id])
  		@content.category.it = it;
  		@it = @content.category.it
		
  		respond_to do |format|
  		  format.html 
  		  format.json { render json: @content }
  		end
	  end
  end

  # POST /contents
  # POST /contents.json
  def create
    it = It.find(params[:it_id])
	  if !it.locked
			@content = params[:content][:type].constantize.new(content_params)
		  @content.title = strip_tags(@content.title)
		  @content.theshiz = sanitize(@content.theshiz)
		  @content.user_id = 0
		  @content.ip = request.remote_ip;
		  @it = @content.category.it
		  
		  time_diff = Shizit::Application.config.content_throttle + 1

			latest = Content.where(ip: @content.ip, in_recycling: false).order(created_at: :desc).first
      
      if latest != nil
        time_diff = Time.now - latest.created_at
      end
      

		  respond_to do |format|
		    if time_diff > Shizit::Application.config.content_throttle
  		    if @content.save
  			     flash[:notice] = 'Content was successfully created.'
  			     format.html { redirect_to it_category_url(@content.category.it, @content.category) }
  			     format.json { render json: @content, status: :created, location: @content }
  		    else
  			     format.html { render action: "new"}
  			     format.json { render json: @content.errors, status: :unprocessable_entity }
  		    end
		    else
		      @content.errors.add("theshiz", "Please wait: " + 
                (Shizit::Application.config.content_throttle).to_s + " seconds. Before posting another.")
          format.html { render action: "new" }
          format.json { render json: @content.errors, status: :unprocessable_entity }
		    end
		  end
	   end
  end
  
  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
	  @content.in_recycling = true
    
    respond_to do |format|
      if (can? :delete, @content)
  		  if @content.save
  		    format.html { redirect_to it_category_url(@content.category.it, @content.category) }
  		    format.json { head :ok }
  		  end
		  end
    end
  end
  
  def pic
	  @content = Content.find(params[:id])
    @image = @content.image_data
    send_data @image, :type => @content.file_type, 
        :filename => @content.file_name, :disposition => 'inline'
	end

	private

	def content_params
		params.require(:content).permit(
			:category_id,
			:type,
			:title,
			:file_type,
			:file_name,
			:theshiz,
			:humanizer_answer,
			:humanizer_question_id,
			:image_file
		)
	end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for([@content.category.it, @content.category, @content], :html => {:multipart => true}) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> Fix the following:</h2>
      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :category_id %>
  Type:<br />
  <%= select("content", "type", 
      ContentType.all.collect {|t| [ t.type_name, t.type_name ] }, 
          {:prompt => 'Select content type'}) %>
  
  <div id="content_title" style="display:none">
	  <%= f.label :title %><br />
	  <%= f.text_field :title %>
  </div>
  <div id="content_code">
  	<%= f.label :file_type, "Language" %><br />
  	<%= f.text_field :file_type %>
  </div>
  <div id="content_pic" style="display:none">
    Please select an image: <br />
	  <%= f.file_field :image_file %> <br /> or
	  Url: <br />
	  <%= f.text_area :file_name, :size=>"40x5" %>
  </div>
  
  <div id="content_shiz" style="display:none">
	  <%= f.label :theshiz %><br />
	  <%= f.text_area :theshiz %>
  </div>

  <br />
  Turing Test:
  <%= f.label :humanizer_answer, @content.humanizer_question %><br />
  <%= f.text_field :humanizer_answer %>
  <%= f.hidden_field :humanizer_question_id %>
  
  <div class="actions">
    <%= f.submit "ShizIt", :id => "post" %>
  </div>
<% end %>

app/views/contents/_list.html.erb
<% if posts.size == 0 %>
No posts! You are lucky to be the first.
<% else %>
  <% posts.each do |post| %>
  <span>
    <% if post.category.is_nsfw %>
      <%= link_to post.title, it_category_content_url(post.category.it, post.category, post),  
      :style => "font-size:" +  (15 + (post.active_comments_count * 1)).to_s + 
      "px;font-weight:" + (15 + (post.active_comments_count * 1)).to_s + ";background-color: #FFB2B2;", 
      :confirm => 'You must be 18 or over to views this content?', :title => post.title %>
    <% else %>
      <%= link_to post.title, it_category_content_url(post.category.it, post.category, post),  
      :style => "font-size:" +  (15 + (post.active_comments_count * 1)).to_s + 
      "px;font-weight:" + (15 + (post.active_comments_count * 1)).to_s,
      :title => post.title %>
    <% end %>
    
    (<%= post.active_comments_count %>) 
  </span>
  <% end %>
<% end %>

app/views/contents/_shiz_summary.html.erb
<%  require 'coderay' %>
<div id="content_item" style="border: 1px solid black; padding: 10px;<%= first %>" class="shadow box_round">
<div style="float:left;width:80%;">
  <div class="content_title">
	<%= link_to content.title, it_category_content_url(content.category.it, 
	         content.category, content)  %>
	<br />
	<%= time_ago_in_words(content.created_at.to_s, include_seconds:true) %> Ago
	</div>
	<div style="display:none;" class="s">
	<% if content.class.name == "Pic" %>
	<div>
		<% if content.image_data != nil %>
			<%= image_tag(pic_it_category_content_url(content.category.it, 
			               content.category,content), :alt => "Pic", :border => 1) %>
		<% else %>
			<%= image_tag(content.file_name, :alt => "Pic", :border => 1) %>
		<% end%>
	</div>
	<% end %>
	<div class="content_shiz">
	  <% case content.class.name %>
		  <% when "Pic" %>
				<%= content.theshiz.gsub("\n", "<br />").html_safe %>
	    <% when "Text" %>
				<%= content.theshiz.gsub("\n", "<br />").html_safe %>
			<% when "Question" %>
				<%= content.theshiz %>
			<% when "Link" %>
				<%= content.render_html.html_safe %>
				<a href="<%= content.theshiz %>" target="_blank" class="smalllink"><%= content.theshiz %></a>
			<% when "Code" %>
				<%= CodeRay.scan(content.theshiz, (content.file_type.presence || 'text').to_sym).div.html_safe %>
			<% end %>
	</div>
	</div>
</div>
<div style="float:left;text-align:center;">
<span style="font-size:30px;color:#E8E8E8;">
<%= content.symbol %>
</span>
</div>
<div id="content_goodies" style="clear:both;font-size:10px;">Comments(<%= content.active_comments_count %>)</div>
</div>

app/views/contents/close.html.erb
<script type="text/javascript">
$(parent.document).find('.ui-dialog');
window.parent.$('#divId').dialog('close');
</script>

app/views/contents/new.html.erb
<script type = "text/javascript">
$(document).ready(function () {
    $("#content_type").change(function () {
        switch($("#content_type").val())
		{
			case 'Pic':
				$("#content_pic").show();
				$("#content_shiz label").text("Description");
				$("#content_title label").text("Title");
				$("#content_shiz textarea").attr("rows", "5");
				$("#content_shiz").show();
				$("#content_title").show();
				$("#post").show();
				$("#content_code").hide();
				break;
			case 'Link':
				$("#content_pic").hide();
				$("#content_shiz label").text("Link");
				$("#content_shiz textarea").attr("rows", "5");
				$("#content_shiz").show();
				$("#content_title").show();
				$("#post").show();
				$("#content_code").hide();
				break;
			case 'Text':
				$("#content_pic").hide();
				$("#content_shiz label").text("Start Typing:");
				$("#content_shiz textarea").attr("rows", "20");
				$("#content_shiz textarea").attr("cols", "50");
				$("#content_shiz").show();
				$("#content_title").show();
				$("#post").show();
				$("#content_code").hide();
				break;
			case 'Question':
				$("#content_title").hide();
				$("#content_shiz label").text("Ask it");
				$("#content_pic").hide();
				$("#content_shiz").show();
				$("#content_shiz textarea").attr("rows", "5");
				$("#post").show();
				$("#content_code").hide();
				break;
			case 'Code':
				$("#content_pic").hide();
				$("#content_shiz label").text("Code");
				$("#content_code").show();
				$("#content_title label").text("Title");
				$("#content_shiz textarea").attr("rows", "5");
				$("#content_shiz").show();
				$("#content_title").show();
				$("#post").show();
				break;
			default:
				$("#content_shiz").hide();
				$("#content_title").hide();
				$("#content_pic").hide();
				$("#post").hide();
				$("#content_code").hide();
				break;
		}
    });
	
	$("#content_type").change();
});

</script>
<%= render 'form' %>

app/views/contents/show.html.erb
<%  require 'coderay' %>
<script>
function showAddDialog(){
	$("#divId").dialog({ title: 'Add a Comment' });
   	$("#divId").dialog("open");
   	$("#modalIframeId").attr("src","<%= new_it_category_content_comment_url(@content.category.it,
   	      @content.category, @content) %>");
   	return false;
}

$(document).ready(function() {
		$("#divId").dialog({
			autoOpen : false,
			modal : true,
			height : 300,
			width : 500,
			stack: false,
			close : function(event, ui) {
				location.reload(true);
			}
		});
});
</script>
<% content_for :shiz_cat do %>
   /<%= link_to @content.category.theshiz, it_category_url(@content.category.it, @content.category)  %>
<% end %>
<% content_for :shiz_cat do %>
	/<%= @content.title %>
<% end %>
<div id="content_item" style="margin:10px;">
<% if (can? :delete, @content) %>
	<%= link_to "X", [@content.category.it, @content.category, @content], 
	         :confirm => 'Are you sure?', 
	                   :method => :delete %>
<% end %>
<div id="content_title">
<h3><%= @content.title %></h3>
<span style="font-size: 12px;">Posted: <%= time_ago_in_words(@content.created_at, include_seconds:true) %> ago</span>
</div>
<% if @content.class.name == "Pic" %>
	<div>
		<% if @content.image_data != nil %>
			<%= image_tag(pic_it_category_content_url(@content.category.it, @content.category,@content), :alt => "Pic", :border => 1) %>
		<% else %>
			<%= image_tag(@content.file_name, :alt => "Pic", :border => 1) %>
		<% end%>
	</div>
<% end %>
<div id="content_shiz" style="border: 1px solid black;padding:10px;background-color:#F8F8F8;">
<% if @content.class.name == "Code" %>
<%= CodeRay.scan(@content.theshiz, @content.file_type).div().html_safe %>
<% elsif @content.class.name == "Link" %>
<%= @content.render_html.html_safe %>
<br />
<a href="<%= @content.theshiz %>" target="_blank" class="smalllink"><%= @content.theshiz %></a>
<% else %>
<%= @content.theshiz.gsub("\n", "<br />").html_safe %>
<% end %>
</div>
<br />
<div id="content_goodies" style="font-size: 13px;">
Comments (<%= @content.comments.count.to_s %>)
</div>
<hr />
</div>
<div style="margin:10px;">
<% if !@content.category.it.locked %>
	<a href="<%= new_it_category_content_comment_url(@content.category.it,
   	      @content.category, @content) %>" class="smalllink">Add Comment</a>
<% end %>
</div>
<div style="border:1px dotted black;padding:10px;margin:10px;">
<% @content.comments.each do |comment|  %>
	<%= render :partial => "comments/comment", :locals=>{:comment=> comment, :notifications => @notifications} %> 
<% end %>
</div>
<div id="divId" title="Modal Window">
    <iframe id="modalIframeId" width="100%" height="100%"
    marginWidth="0" marginHeight="0" frameBorder="0" scrolling="no"
    title="Dialog Title">Your browser does not support javascript</iframe>
</div>