config/routes.rb
Shizit::Application.routes.draw do
	get '/activity', to: 'its#activity'

	resources :its do
		member do
			get 'activity'
		end

		resources :categories do
			resources :contents do
				member do
					get 'pic'
				end
				resources :comments
			end
		end
	end

	devise_for :users

	root to: 'its#show'
end

app/models/it.rb
class It < ActiveRecord::Base
	has_many :categories, :dependent => :destroy
	
	def to_param
		"#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
	end
end

app/controllers/it_controller.rb
class ItController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
	def index
	    @it = It.where(:is_current => true).first
	    @its = It.find(:all, :order => "created_at DESC")
	end
	
	def show
	   @it = params[:id].nil? ? It.where(:is_current => true).first : It.find(params[:id])
	   @categories = Category.find_all_by_it_id(@it.id)
	   if(current_user != nil)
	     @notifications = Notification.where(:user_id => current_user.id, :type_name => "Category").all
	     if @notifications != nil
  	     @notifications.each do |notification|
  	       seek = Notification.find_all_by_user_id_and_parent_type_id(current_user.id, notification.type_id)
  	       if seek.empty?
  	         Notification.delete(notification.id)
  	       end
  	     end
	     end
	     
	     @notifications = Notification.where(:user_id => current_user.id, :type_name => "Category").all
	     
	   end
	end
	
	def you
	  @it = params[:id].nil? ? It.where(:is_current => true).first : It.find(params[:id])
	  @categories = Category.find_all_by_user_id_and_it_id(current_user.id, @it.id).sort_by{|category| category.contents.count}
	  @contents = Content.joins(:category).where(:user_id => current_user.id, 
	             :categories => { :it_id => @it.id, :in_recycling => false}).all.sort_by{|content| content.comments.count}
	  @contents.reverse!
	  @comments = Comment.joins(:content => [:category]).where(:user_id => current_user.id,
	         :contents => {:in_recycling => false} ,:categories => {:it_id => @it.id, :in_recycling => false}).all
	  
	  @commented_contents = Array.new
	  @comments.each do |comment|
	    @commented_contents << comment.content
	  end
	  
	  @commented_contents.uniq!
	  @shiz_score = @categories.count + @contents.count + (@comments.count / 5)
	end
end

app/controllers/its_controller.rb
class ItsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :activity]
  
  def new 
    @new_it = It.new 
    @it = It.where(:is_default => true).first
    if (can? :create, @comment)
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @new_it }
      end
    end
  end
  
  def create
    @new_it = It.new(params[:it])
    if (can? :create, @new_it)
      respond_to do |format|
        if @new_it.save
          flash[:notice] = 'It was successfully created.'
          if @new_it.is_default
            @its = It.find(:all)
            @its.each do |t|
              if t.id != @new_it.id
                t.is_default = false
                t.save
              end
            end
          end
          
          format.html { redirect_to its_path, notice: 'It was successfully created.' }
          format.json { render json: @new_it, status: :created, location: @new_it }
        else
          format.html { render action: "new" }
          format.json { render json: @new_it.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
	def index
	    @it = It.where(:is_default => true).first
      @its = It.order(created_at: :desc)
	end

  def show
    @view = params[:view].nil? ? "category" : params[:view]
    @it = params[:id].nil? ? It.where(:is_default => true).first : It.find(params[:id])
    @recent_post = Content.order('created_at DESC').limit(20)
    @popular_post = Content.order('click_count DESC').limit(20)
    @popular = @popular_post  # <- added this line for your view
    if @view == "posts"
      @posts = Content.includes(:category)
                      .joins(:category)
                      .where("categories.in_recycling = ? and categories.it_id = ?", false, @it.id)
    else
      @categories = Category.where(it_id: @it.id)
    end
  end

	
	def edit
	   @new_it = It.find(params[:id])
	   @it = It.where(:is_default => true).first
	end
	
	def update
	  @new_it = It.find(params[:id])
	  if (can? :update, @new_it)
  	  respond_to do |format|
        if @new_it.update_attributes(params[:it])
          if @new_it.is_default
            @its = It.find(:all)
            @its.each do |t|
              if t.id != @new_it.id
                t.is_default = false
                t.save
              end
            end
          end
          
          format.html { redirect_to its_path, notice: 'It was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @new_it.errors, status: :unprocessable_entity }
        end
      end
	  end
	end
	
	def activity
    @recent_post = Content.order('created_at DESC').limit(20)
    @popular_post = Content.order('click_count DESC').limit(20)
    @recent_categories = Category.order('created_at DESC').limit(20)
    @popular_categories = Category.order('click_count DESC').limit(20)
    @recent_comments = Comment.order('created_at DESC').limit(20)
    @category_count = Category.count
    @post_count = Content.count
    @comment_count = Comment.count
	end
end

app/helpers/it_helper.rb
module ItHelper
end

app/views/its/_form.html.erb
<%= form_for(@new_it) do |f|%>
  <% if @new_it.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_it.errors.count, "error") %> sh!z blocked, Fix the following YO!:</h2>
      <ul>
      <% @new_it.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :is_default %>
  <%= f.check_box :is_default %><br />
  </div>
  <div>
  <%= f.label :locked %>
  <%= f.check_box :locked %><br />
  </div>
  
  <div>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/its/activity.html.erb
<div style="width:70%;margin:0 auto;">
<div>
  Recent Comments:<br />
  <% @recent_comments.each do |comment| %>
    <% if comment.content != nil%>
    <span>
    <p class="comments">
    <%= comment.comment_text.html_safe %><br />
    <%= link_to "link", it_category_content_url(comment.content.category.it, 
           comment.content.category, comment.content), :style => "font-size:12px;" %>
    </p>
    </span>
    <% end %>
  <% end %>
</div>
<div>
<div>
  Recent Posts:<br />
  <% @recent_post.each do |post| %>
  <span>
  <p style="border: 1px solid black;background: lightgrey;font-size: 12px;">
  <%= link_to post.title, it_category_content_url(post.category.it, 
           post.category, post)  %><br />
    <b>Views:</b> <%= post.click_count %>
    <b>Comments:</b> <%= post.active_comments_count %><br />
    <b>Created:</b> <%= post.created_at.to_s %> 
  </p>
  <% end %>
</div>
<div>
  Popular Posts:<br />
  <% @popular_post.each do |post| %>
  <p style="border: 1px solid black;background: lightgrey;font-size: 12px;">
  <%= link_to post.title, it_category_content_url(post.category.it, 
           post.category, post)  %><br />
    <b>Views:</b> <%= post.click_count %>
    <b>Comments:</b> <%= post.active_comments_count %><br />
    <b>Created:</b> <%= post.created_at.to_s %> 
  </p>
  <% end %>
</div>
<div>
  Recent Categories:<br />
  <% @recent_categories.each do |category| %>
  <span>
  <p style="border: 1px solid black;background: lightgrey;font-size: 12px;">
    <%= link_to category.theshiz, it_category_url(category.it, category), :title => category.theshiz %>
    <br />
    <b>Views:</b> <%= category.click_count %>
    <b>Posts:</b> <%= category.active_contents_count %><br />
    <b>Created:</b> <%= category.created_at.to_s %> 
  </p>
  </span>
  <% end %>
</div>
<div>
  Popular Categories:<br />
  <% @popular_categories.each do |category| %>
  <span>
  <p style="border: 1px solid black;background: lightgrey;font-size: 12px;">
      <%= link_to category.theshiz, it_category_url(category.it, category), :title => category.theshiz %>
      <br />
      <b>Views:</b> <%= category.click_count %>
      <b>Posts:</b> <%= category.active_contents_count %><br />
      <b>Created:</b> <%= category.created_at.to_s %> 
  </p>
  </span>
  <% end %>
</div>
</div>
<div style="clear:both;"></div>
</div>

app/views/its/edit.html.erb
<%= render 'form' %>

app/views/its/index.html.erb
<% if (can? :create, It.new) %>
<%= link_to "new", new_it_path %>
<hr style="border: 1px dashed #000;"/>
<% end %>
<% @its.each do |it| %>
<div>
	<div>
	<% if it.is_default%>
		<span style="color: green"><%= link_to it.name,  it %><--- Current Shiz</span>
	<% else %>
		<span><%= link_to it.name,  it %></span>
	<% end %>
	<% if (can? :create, it) %>
		|| <%= link_to "Edit", edit_it_path(it)%>
	<%end%>
	</div>
	<div><%= it.created_at.to_date %></div>
</div>
<% end %>

app/views/its/new.html.erb
<%= render 'form' %>

app/views/its/show.html.erb
<script>
function showAddDialog(){
	$("#divId").dialog({ title: '<%=t :add_category_title %>' });
   	$("#divId").dialog("open");
   	$("#modalIframeId").attr("src","<%= new_it_category_url(@it) %>");
   	return false;
}

$(document).ready(function() {
		$("#divId").dialog({
			autoOpen : false,
			modal : true,
			height : 400,
			width : 500,
			position: [100,50],
			close : function(event, ui) {
				location.reload(true);
			}
		});
});
</script>

<div id="recent_posts">
	Recent Post:
	<% @recent_post.each do |post| %>
  	<% title  = ""%>
  	<% if post.class.name == "Question" %> 
  	 <% title = post.theshiz %>
  	<% else %> 
  	 <% title = post.title %>
  	<% end %>
  	
  	<% if post.category != nil %>
  	 <%= link_to truncate(title,:length => 20, :ommission => "..."), 
  	   it_category_content_url(post.category.it, 
  	   post.category, post), :class => "pop", :title => title %> 
  	   &nbsp;
  	<% end %> 
  <% end %>
</div>
<div style="width:70%;text-align: left;margin:0 auto;">Anonymous content posting</div>
<br />
<% if !@it.locked && @view == "category" %>
	<div style="width:70%;text-align: left;margin:0 auto;">
	  <a href="<%= new_it_category_url(@it) %>" class="smalllink">
	    <%=t :add_category_button %>
	  </a>
	  •
	  <a href="/its/<%= @it.to_param %>?view=posts" title="Posts Cloud" class="smalllink">
      Post Cloud</a>
    •
	  <a href="../activity" class="smalllink">Activity</a>
	</div> 
<% else %>
<div style="width:70%;text-align: left;margin:0 auto;">
    <a href="/its/<%= @it.to_param %>" title="Back to category cloud" class="smalllink">
      Category Cloud</a>
    •
    <a href="../activity" class="smalllink">Activity</a>
  </div> 
<% end %>
<div id="category">
<% if @view == "posts"%>
<%= render :partial => "contents/list", 
  :locals=>{:posts=> @posts} %> 
<% else %>

<%= render :partial => "categories/list", 
  :locals=>{:categories=> @categories, :notifications => @notifications} %> 

<% end %>
</div>
<br />
<div id="most_viewed">
  Most Viewed:
  <% @popular.each do |post| %>
  	<% title  = ""%>
  	<% if post.class.name == "Question" %> 
  	 <% title = post.theshiz %>
  	<% else %> 
  	 <% title = post.title %>
  	<% end %>
  	
  	<% if post.category != nil %>
  		<%= link_to truncate(title,:length => 20, :ommission => "..."), 
  		it_category_content_url(post.category.it, post.category, post), :class => "pop", :title => title %>
  		&nbsp;
  	<% end %> 
  <% end %>
</div>

<div id="divId" title="Modal Window">
    <iframe id="modalIframeId" width="100%" height="100%"
    marginWidth="0" marginHeight="0" frameBorder="0" scrolling="no"
    title="Dialog Title">Your browser does not support javascript</iframe>
</div>