config/routes.rb
Shizit::Application.routes.draw do
	get '/activity', to: 'its#activity'

	resources :its do
		member do
			get 'activity'
		end

		resources :categories do
			resources :contents do
				member do
					get 'pic'
				end
				resources :comments
			end
		end
	end

	devise_for :users

	root to: 'its#show'
end

app/models/it.rb
class It < ActiveRecord::Base
	has_many :categories, :dependent => :destroy
	
	def to_param
		"#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
	end
end

app/controllers/it_controller.rb
class ItController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
	def index
	    @it = It.where(:is_current => true).first
	    @its = It.find(:all, :order => "created_at DESC")
	end
	
	def show
	   @it = params[:id].nil? ? It.where(:is_current => true).first : It.find(params[:id])
	   @categories = Category.find_all_by_it_id(@it.id)
	   if(current_user != nil)
	     @notifications = Notification.where(:user_id => current_user.id, :type_name => "Category").all
	     if @notifications != nil
  	     @notifications.each do |notification|
  	       seek = Notification.find_all_by_user_id_and_parent_type_id(current_user.id, notification.type_id)
  	       if seek.empty?
  	         Notification.delete(notification.id)
  	       end
  	     end
	     end
	     
	     @notifications = Notification.where(:user_id => current_user.id, :type_name => "Category").all
	     
	   end
	end
	
	def you
	  @it = params[:id].nil? ? It.where(:is_current => true).first : It.find(params[:id])
	  @categories = Category.find_all_by_user_id_and_it_id(current_user.id, @it.id).sort_by{|category| category.contents.count}
	  @contents = Content.joins(:category).where(:user_id => current_user.id, 
	             :categories => { :it_id => @it.id, :in_recycling => false}).all.sort_by{|content| content.comments.count}
	  @contents.reverse!
	  @comments = Comment.joins(:content => [:category]).where(:user_id => current_user.id,
	         :contents => {:in_recycling => false} ,:categories => {:it_id => @it.id, :in_recycling => false}).all
	  
	  @commented_contents = Array.new
	  @comments.each do |comment|
	    @commented_contents << comment.content
	  end
	  
	  @commented_contents.uniq!
	  @shiz_score = @categories.count + @contents.count + (@comments.count / 5)
	end
end

app/controllers/its_controller.rb
class ItsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :activity]
  
  def new 
    @new_it = It.new 
    @it = It.where(:is_default => true).first
    if (can? :create, @comment)
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @new_it }
      end
    end
  end
  
  def create
    @new_it = It.new(params[:it])
    if (can? :create, @new_it)
      respond_to do |format|
        if @new_it.save
          flash[:notice] = 'It was successfully created.'
          if @new_it.is_default
            @its = It.find(:all)
            @its.each do |t|
              if t.id != @new_it.id
                t.is_default = false
                t.save
              end
            end
          end
          
          format.html { redirect_to its_path, notice: 'It was successfully created.' }
          format.json { render json: @new_it, status: :created, location: @new_it }
        else
          format.html { render action: "new" }
          format.json { render json: @new_it.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
	def index
	    @it = It.where(:is_default => true).first
      @its = It.order(created_at: :desc)
	end

  def show
    @view = params[:view].nil? ? "category" : params[:view]
    @it = params[:id].nil? ? It.where(:is_default => true).first : It.find(params[:id])
    @recent_post = Content.order('created_at DESC').limit(20)
    @popular_post = Content.order('click_count DESC').limit(20)
    @popular = @popular_post  # <- added this line for your view
    if @view == "posts"
      @posts = Content.includes(:category)
                      .joins(:category)
                      .where("categories.in_recycling = ? and categories.it_id = ?", false, @it.id)
    else
      @categories = Category.where(it_id: @it.id)
    end
  end

	
	def edit
	   @new_it = It.find(params[:id])
	   @it = It.where(:is_default => true).first
	end
	
	def update
	  @new_it = It.find(params[:id])
	  if (can? :update, @new_it)
  	  respond_to do |format|
        if @new_it.update_attributes(params[:it])
          if @new_it.is_default
            @its = It.find(:all)
            @its.each do |t|
              if t.id != @new_it.id
                t.is_default = false
                t.save
              end
            end
          end
          
          format.html { redirect_to its_path, notice: 'It was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @new_it.errors, status: :unprocessable_entity }
        end
      end
	  end
	end
	
	def activity
    @recent_post = Content.order('created_at DESC').limit(20)
    @popular_post = Content.order('click_count DESC').limit(20)
    @recent_categories = Category.order('created_at DESC').limit(20)
    @popular_categories = Category.order('click_count DESC').limit(20)
    @recent_comments = Comment.order('created_at DESC').limit(20)
    @category_count = Category.count
    @post_count = Content.count
    @comment_count = Comment.count
	end
end

app/helpers/it_helper.rb
module ItHelper
end

app/views/it/index.html.erb
<% @its.each do |it| %>
<div>
	<div>
	
	<% if it.is_current%>
		<span style="color: green"><%= link_to it.name,  it %><--- Current Shiz</span>
	<% else %>
		<span><%= link_to it.name,  it %></span>
	<% end %>
	</div>
	<div><%= it.created_at %></div>
<div>

<% end %>

app/views/it/show.html.erb
<script>
function showAddDialog(){
	$("#divId").dialog({ title: '<%=t :add_category_title %>' });
   	$("#divId").dialog("open");
   	$("#modalIframeId").attr("src","<%= new_it_category_url(@it) %>");
   	return false;
}

$(document).ready(function() {
		$("#divId").dialog({
			autoOpen : false,
			modal : true,
			height : 400,
			width : 500,
			position: [100,50],
			close : function(event, ui) {
				location.reload(true);
			}
		});
});
</script>
<span><%= @it.message %></span><span style="float:right;">:)<%= link_to t(:archive_link) , it_index_path %>(:</span>
<br />
<% if @it.is_current %>
<input type="button" id="add" value="<%=t :add_category_button %>" onclick="return showAddDialog()">
<% end %>
<div id="category" style="width:70%;">
<%= render :partial => "categories/list", :locals=>{:categories=> @categories, :notifications => @notifications} %> 
</div>

<div id="divId" title="Modal Window">
    <iframe id="modalIframeId" width="100%" height="100%"
    marginWidth="0" marginHeight="0" frameBorder="0" scrolling="no"
    title="Dialog Title">Your browser does not support javascript</iframe>
</div>