config/routes.rb
Shizit::Application.routes.draw do
	get '/activity', to: 'its#activity'

	resources :its do
		member do
			get 'activity'
		end

		resources :categories do
			resources :contents do
				member do
					get 'pic'
				end
				resources :comments
			end
		end
	end

	devise_for :users

	root to: 'its#show'
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Humanizer
  require_human_on :create
	default_scope { where(in_recycling: false) }
	validates :theshiz, :presence => true, :length => { :maximum => 20 }, :uniqueness => { :scope => :it_id,
    :message => "This category has already been created" }
	has_many :contents
	belongs_to :it, :counter_cache => true
	
	
	def to_param
		"#{id}-#{theshiz.gsub(/[^a-z0-9]+/i, '-')}"
	end
	
	def get_total_points
	  total = self.contents.count
	  
	  self.contents.each do |content|
	    total += content.comments.count / 4
	  end
	  
	  total
	end
	
	def update_click_counter
    self.click_count = self.click_count + 1
    self.save
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_filter :authenticate_user!, :except => [:show, :create]
  load_and_authorize_resource :only => [:delete, :update]
 
  # GET /categories/1
  # GET /categories/1.json
  def show
    @sort = params[:sort].nil? ? "pop" : params[:sort]
    @category = Category.find(params[:id])
    @category.update_click_counter
    
    page = params[:page].nil? ? 1 : params[:page]
    
	  if @sort == "recent"
		  @contents = Content.where(:category_id => params[:id]).paginate(:page => page).order('created_at DESC')
	  else
		  @contents = Content.where(:category_id => params[:id]).paginate(:page => page).order('active_comments_count DESC')
	  end
    #application layout page needs this
	  @it = @category.it
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
  	it = It.find(params[:it_id])
  	
  	if !it.locked
  		@category = Category.new
  		@category.it = it
  		
  		respond_to do |format|
  		  format.html  {render :layout => "application"}# new.html.erb
  		  format.json { render json: @category }
  		end
  	end
  end

  # POST /categories
  # POST /categories.json
	def create
		it = It.find(params[:it_id])
		if !it.locked
			@category = Category.new(category_params)
			@category.it = it
			@category.user_id = 0
			@category.ip = request.remote_ip

			time_diff = Shizit::Application.config.category_throttle + 1
			latest = Category.where(ip: @category.ip).order('created_at DESC').limit(1).first

			time_diff = Time.now - latest.created_at if latest.present?

			respond_to do |format|
				if time_diff > Shizit::Application.config.category_throttle
					if @category.save
						flash[:notice] = 'Category was successfully created.'
						format.html { redirect_to it_url(@category.it) }
						format.json { render json: @category, status: :created, location: @category }
					else
						format.html { render action: "new" }
						format.json { render json: @category.errors, status: :unprocessable_entity }
					end
				else
					@category.errors.add(:theshiz, "Please wait: #{Shizit::Application.config.category_throttle} seconds before creating another category.")
					format.html { render action: "new" }
					format.json { render json: @category.errors, status: :unprocessable_entity }
				end
			end
		end
	end

	# DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    
    if (can? :delete, @category)
  	  @category.in_recycling = true
  
  	  if @category.save
  		  respond_to do |format|
  		    format.html { redirect_to "/" }
  		    format.json { head :ok }
  		  end
  	  end
	  end
	end

	private

	def category_params
		params.require(:category).permit(:theshiz, :is_nsfw, :humanizer_answer, :humanizer_question_id)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for([@category.it, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> Fix the following:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :theshiz %>
  <br />
  <%= f.label :is_nsfw %>
  <%= f.check_box :is_nsfw %> <br />
  <br />
  Turing Test:
  <%= f.label :humanizer_answer, @category.humanizer_question %>
  <%= f.text_field :humanizer_answer %>
  <%= f.hidden_field :humanizer_question_id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<% if categories.size == 0 %>
Virgin Board! Be the first to create a category.
<% else %>
	<% categories.each do |category| %>
	<span>
	  <% if category.is_nsfw %>
	    <%= link_to category.theshiz, it_category_url(category.it, category),  
		  :style => "font-size:" +  (15 + (category.get_total_points * 1)).to_s + 
		  "px;font-weight:" + (15 + (category.get_total_points * 1)).to_s + ";background-color: #FFB2B2;", 
		  :confirm => 'You must be 18 or over to views this content?', :title => category.theshiz %>
	  <% else %>
	    <%= link_to category.theshiz, it_category_url(category.it, category),  
		  :style => "font-size:" +  (15 + (category.get_total_points * 1)).to_s + 
		  "px;font-weight:" + (15 + (category.get_total_points * 1)).to_s,
		  :title => category.theshiz %>
	  <% end %>
	  
	  (<%= category.active_contents_count %>) 
	  
	  <% if can? :delete, category %>
	    <%= link_to "X", it_category_path(category.it, category), 
	      :confirm => 'Are you sure?', :method => :delete %>
	  <% end %>
	</span>
	<% end %>
<% end %>

app/views/categories/close.html.erb
<script type="text/javascript">
$(parent.document).find('.ui-dialog');
window.parent.$('#divId').dialog('close');
</script>

app/views/categories/new.html.erb
<h4>Create a new category</h4>
<%= render 'form' %>

app/views/categories/show.html.erb
<script>
function expand_all()
{
	alert('hide');
	$('div.s').toggle(
		
		function () {
               $('div.s').show();
         },
         function () {
                $('div.s').hide();
         }	
	);
	
	return false;
}

$(document).ready(function() {
		 $('a.toggle').toggle(
			function () {
			   if($(this).text() == "-")
			   {
			   		$(this).text("+");
			   }
			   else
			   {
			   	  $(this).text("-");
			   }
               
               $(this).parent('div').next('div').toggle();
            },
            function () {
               if($(this).text() == "-")
			   {
			   		$(this).text("+");
			   }
			   else
			   {
			   	  $(this).text("-");
			   }
                $(this).parent('div').next('div').toggle();
            }
		 );
		 
		 $('a[name="expand"]').toggle(
		 	function () {
               $('div.s').show();
               $(this).text("-");
               $('.toggle').text("-");
            },
            function () {
               $('div.s').hide();
               $(this).text("+");
               $('.toggle').text("+");
            }	 	
		 );
});

</script>
<div style="width:70%;text-align: center;margin:0 auto;"><%= image_tag("footer.png") %></div>
<% content_for :shiz_cat do %>
   /<%= @category.theshiz %>
<% end %>
<div style="width:70%;margin:0 auto;">
<div id="content" style="float:left;width:100%;">
<% if !@category.it.locked %>
<%= link_to "add", new_it_category_content_url(@category.it, @category), :class => "smalllink" %>
<% end %>
<% if @sort == "recent" %>
<span style="float:right;"> || View By: <%= link_to "Popularity", it_category_url(@category.it, @category) +  "?sort=pop" , :class => "smalllink"%></span>
<% else %>
<span style="float:right;"> || View By: <%= link_to "Recent", it_category_url(@category.it, @category) +  "?sort=recent" , :class => "smalllink"%></span>
<% end %>
<a href="#" style="float:right;padding-right:5px;" name="expand" class="smalllink">+</a><br />
<% first = "background-color:#E6F5FF;" %>
<% @contents.each do |content|  %>
	<%= render :partial => "contents/shiz_summary", :locals=>{:content=> content, :first => first} %> 
	<% first = ""%>
<% end %>
</div>
<div style="clear:both;"></div>
<%= will_paginate @contents %>
</div>
<br />
<br />